name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # ÙŠØªÙ… Ø§Ù„ØªØ­Ø¯ÙŠØ« ÙŠÙˆÙ…ÙŠÙ‹Ø§ Ø§Ù„Ø³Ø§Ø¹Ø© 12 ØµØ¨Ø§Ø­Ù‹Ø§ UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake SVG animation
        uses: Platane/snk@v3
        with:
          github_user_name: ahmedshaban-blip
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push the snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
